jqver: "2.1.1"
jquiver: "1.11.4"
jqmver: "1.4.5"
bsver: "3.3.7"
dbver: "-4.4.2"
dbverdir: "4.4.2"
cdn: "https://cdn.jtsage.com/jtsage-datebox/"
i18n: "https://cdn.jtsage.com/jtsage-datebox/i18n/"
highlighter: rouge
markdown: kramdown
permalink: pretty
basesite: "https://jtsage.dev/DateBox/"
min: ".min"

