jqver: "2.1.1"
jquiver: "1.11.4"
jqmver: "1.4.5"
bsver: "3.3.7"
dbver: "-4.1.2"
dbverdir: "4.1.2"
cdn: "http://cdn.jtsage.com/jtsage-datebox/"
i18n: "http://cdn.jtsage.com/jtsage-datebox/i18n/"
highlighter: rouge
markdown: kramdown
permalink: pretty
basesite: "http://dev.jtsage.com/DateBox/"
min: ".min"

